# MACHINE LEARNING

## Final Project 

### Submitted To : Prof. Shifali Sharma
### Submitted By : Hrithik Johri









#### Importing require libraries

In [1]:
# warnings ignored

import warnings
warnings.filterwarnings('ignore')

In [3]:
#importing libraries....

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import scale
%matplotlib inline

In [4]:
#importing database..

df = pd.read_csv('2.csv')


In [5]:
#shape of database
df.shape

(1728, 7)

In [6]:
#head of the database
df.head()

buying  maint doors persons lug_boot safety    car
0  vhigh  vhigh   two     two    small    low  unacc
1  vhigh  vhigh   two     two    small    med  unacc
2  vhigh  vhigh   two     two    small   high  unacc
3  vhigh  vhigh   two     two      med    low  unacc
4  vhigh  vhigh   two     two      med    med  unacc

In [7]:
# showing categorical and continuous datatypes

df.dtypes

buying      object
maint       object
doors       object
persons     object
lug_boot    object
safety      object
car         object
dtype: object

In [8]:
# checking the null values
df.isna().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
car         0
dtype: int64

## Slicing dependent and independent variables from dataframe

In [9]:
# Extracting the dependent and independent variable
Y=df['car']
X=df.drop(columns='car')

In [10]:
# head of the feature variable dataset
X.head()

buying  maint doors persons lug_boot safety
0  vhigh  vhigh   two     two    small    low
1  vhigh  vhigh   two     two    small    med
2  vhigh  vhigh   two     two    small   high
3  vhigh  vhigh   two     two      med    low
4  vhigh  vhigh   two     two      med    med

In [11]:
# converting the categorical values to continuous variable

df1=pd.get_dummies(X,drop_first=True)

In [12]:
df1.shape

(1728, 15)

In [13]:
# display the  head in df dataframe

df1.head()

buying_low  buying_med  buying_vhigh  maint_low  maint_med  maint_vhigh  \
0           0           0             1          0          0            1   
1           0           0             1          0          0            1   
2           0           0             1          0          0            1   
3           0           0             1          0          0            1   
4           0           0             1          0          0            1   

   doors_four  doors_three  doors_two  persons_more  persons_two  \
0           0            0          1             0            1   
1           0            0          1             0            1   
2           0            0          1             0            1   
3           0            0          1             0            1   
4           0            0          1             0            1   

   lug_boot_med  lug_boot_small  safety_low  safety_med  
0             0               1           1           0  
1             0               1           0           1  
2             0               1           0           0  
3             1               0           1           0  
4             1               0           0           1

In [14]:
X.dtypes

buying      object
maint       object
doors       object
persons     object
lug_boot    object
safety      object
dtype: object

In [15]:
Y.unique()

array(['unacc', 'acc', 'vgood', 'good'], dtype=object)

In [20]:
#converting the categorical target variable to continuous variable

st=[]
for i in Y:
    if(i=='unacc'):
        st.append(4)
    elif(i=='acc'):
        st.append(3)
    elif(i=='vgood'):
        st.append(2)
    elif(i=='good'):
        st.append(1)

### Splitting Dataset into Train and test

In [21]:


X_train,X_test,Y_train,Y_test=train_test_split(df1,Y,test_size=0.40,random_state=42)

In [22]:

#converting the list to dataframe
Y=pd.DataFrame(st,columns=['car'])
Y.head()


car
0    4
1    4
2    4
3    4
4    4

# Model Building

## Building Linear model

In [23]:
#linear model

linear_model=SVC(kernel='linear')
linear_model.fit(X_train,Y_train)

#predict
Y_pred=linear_model.predict(X_test)

In [25]:
## confusion matrix and accuracy

print("Accuracy of lenar model:",metrics.accuracy_score(y_true=Y_test,y_pred=Y_pred),"\n")

#confusion matrix

print(metrics.confusion_matrix(y_true=Y_test,y_pred=Y_pred))

Accuracy of lenar model: 0.9248554913294798 

[[142   4  14   0]
 [  5  18   0   3]
 [ 18   0 463   0]
 [  8   0   0  17]]


**Linear model accuracy is:~92**



## Non-linear model

In [26]:
#Non-linear model
non_linear_model=SVC(kernel='rbf')
non_linear_model.fit(X_train,Y_train)
y_pred=non_linear_model.predict(X_test)

In [27]:
#Accuracy

print("Accuracy:",metrics.accuracy_score(y_true=Y_test,y_pred=Y_pred))

#Confusion matrix

print(metrics.confusion_matrix(y_true=Y_test,y_pred=Y_pred))

Accuracy: 0.9248554913294798
[[142   4  14   0]
 [  5  18   0   3]
 [ 18   0 463   0]
 [  8   0   0  17]]


**Non-linear model accuracy:~92**

## GridSearch Hypertuning for Choosing best parameters

In [35]:
#GridSearch Hyprertuning

folds=KFold(n_splits=5,shuffle=True,random_state=101)

hyper_params=[{'gamma':[2,4,6,8,10],'C':[3,5,7,9,10]}]

model=SVC(kernel='rbf')
model_cv=GridSearchCV(estimator=model,param_grid=hyper_params,scoring='accuracy',
                     cv=folds,verbose=1,return_train_score=True)

model_cv.fit(x_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits


[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed:   29.5s finished


GridSearchCV(cv=KFold(n_splits=5, random_state=101, shuffle=True),
       error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'gamma': [2, 4, 6, 8, 10], 'C': [3, 5, 7, 9, 10]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='accuracy', verbose=1)

In [30]:
# cv results

results = pd.DataFrame(model_cv.cv_results_)
results

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.169363      0.024590         0.014863        0.001349       3   
1        0.202719      0.063613         0.014264        0.003810       3   
2        0.192389      0.018349         0.016156        0.006132       3   
3        0.316800      0.230847         0.018847        0.012618       3   
4        0.223567      0.034385         0.023036        0.013166       3   
5        0.242080      0.093865         0.019944        0.010307       5   
6        0.249622      0.122426         0.022339        0.013768       5   
7        0.308862      0.107449         0.019745        0.007173       5   
8        0.227214      0.120883         0.016351        0.005869       5   
9        0.257638      0.100142         0.014558        0.006864       5   
10       0.222913      0.111318         0.015758        0.005689       7   
11       0.233372      0.103508         0.013360        0.005871       7   
12       0.169773      0.017108         0.015760        0.004112       7   
13       0.173330      0.008630         0.021344        0.022769       7   
14       0.154679      0.009655         0.013968        0.001267       7   
15       0.138235      0.017598         0.012562        0.002790       9   
16       0.209436      0.066738         0.014763        0.007670       9   
17       0.182424      0.018176         0.016360        0.002642       9   
18       0.160187      0.012495         0.018252        0.006610       9   
19       0.159034      0.010628         0.016259        0.010401       9   

   param_gamma                 params  split0_test_score  split1_test_score  \
0            2   {'C': 3, 'gamma': 2}           0.812500           0.806763   
1            4   {'C': 3, 'gamma': 4}           0.692308           0.724638   
2            6   {'C': 3, 'gamma': 6}           0.692308           0.724638   
3            8   {'C': 3, 'gamma': 8}           0.692308           0.724638   
4           10  {'C': 3, 'gamma': 10}           0.692308           0.724638   
5            2   {'C': 5, 'gamma': 2}           0.812500           0.806763   
6            4   {'C': 5, 'gamma': 4}           0.692308           0.724638   
7            6   {'C': 5, 'gamma': 6}           0.692308           0.724638   
8            8   {'C': 5, 'gamma': 8}           0.692308           0.724638   
9           10  {'C': 5, 'gamma': 10}           0.692308           0.724638   
10           2   {'C': 7, 'gamma': 2}           0.812500           0.806763   
11           4   {'C': 7, 'gamma': 4}           0.692308           0.724638   
12           6   {'C': 7, 'gamma': 6}           0.692308           0.724638   
13           8   {'C': 7, 'gamma': 8}           0.692308           0.724638   
14          10  {'C': 7, 'gamma': 10}           0.692308           0.724638   
15           2   {'C': 9, 'gamma': 2}           0.812500           0.806763   
16           4   {'C': 9, 'gamma': 4}           0.692308           0.724638   
17           6   {'C': 9, 'gamma': 6}           0.692308           0.724638   
18           8   {'C': 9, 'gamma': 8}           0.692308           0.724638   
19          10  {'C': 9, 'gamma': 10}           0.692308           0.724638   

    split2_test_score       ...         mean_test_score  std_test_score  \
0            0.763285       ...                0.800193        0.021394   
1            0.685990       ...                0.703668        0.017235   
2            0.685990       ...                0.703668        0.017235   
3            0.685990       ...                0.703668        0.017235   
4            0.685990       ...                0.703668        0.017235   
5            0.763285       ...                0.800193        0.021394   
6            0.685990       ...                0.703668        0.017235   
7            0.685990       ...                0.703668        0.017235   
8            0.685990       ...                0.703668        0.017235 

In [33]:
# printing the optimal accuracy score and hyperparameters

score = model_cv.best_score_
hyperparams = model_cv.best_params_

In [34]:
print("The best test score is {0} corresponding to hyperparameters {1}".format(score, hyperparams))

The best test score is 0.8001930501930502 corresponding to hyperparameters {'C': 3, 'gamma': 2}


**Best test Score is: 0.8001930501930502<br>
and Hyperparameters {'C': 3, 'gamma': 2}
**

In [71]:
# model with optimal hyperparameters

# model
model = SVC(C=3, gamma=2, kernel="rbf")
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

# metrics

print("accuracy", metrics.accuracy_score(y_test, y_pred), "\n")
print(metrics.confusion_matrix(y_test, y_pred), "\n")

C:\Users\Tarun\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


accuracy 0.8497109826589595 

[[  1   0   2  32]
 [  0   4   4  12]
 [  0   0 100  53]
 [  0   0   1 483]] 



## Accuracy of the final model:
**Linear model:~92<br>
And, in Non-linear model:~84, 
with htyperparameters  C=3 and Gamma=2**